### ISSUE TITLE
Depth Maps for OULU-NPU

### ISSUE THREAD

**Issue by CuauSuarez** [ZitongYu/CDCN#14]
First of all, thank you very much for providing your code.

Reading through, i realized that you have some files with depth maps and others with bounding boxes, how did you obtain this? as the OULU dataset does not include any of them (just info of the position of the eyes).

Thank you

**Comment by ZitongYu** [comment]
bbox is extracted with MTCNN; depth map is via PRNet

**Comment by punitha-valli** [comment]
Can you please tell me about the map_dir,
Then, also about the train_iamges directory

I have the oulu-npu dataset

It will be a great help to my research work

Thanks in advance

**Comment by punitha-valli** [comment]
@ZitongYu 
@CuauLuzbel 
@punitha-valli 

Can you please tell me about the map_dir,
Then, also about the train_iamges directory

I have the oulu-npu dataset

It will be a great help to my research work

Thanks in advance

**Comment by luan1412167** [comment]
@punitha-valli @ZitongYu Can you share me how to arrange training data folder?

**Comment by punitha-valli** [comment]
You need to split the videos into frames
And use the dataloader as per the source code
My Best wishes

Thank you

**Comment by luan1412167** [comment]
@punitha-valli  I dont know what is 6_3_20_5_121_scene.dat and info_list file ?
Can you help me clarify it?

**Comment by punitha-valli** [comment]
it is about the boundary box,

You can obtain the boundary box from MTCNN, it is used to extract the face
region from the image

**Comment by busrasi** [comment]
I have used OULU dataset to train the model. When I run train_CDCN.py I get the error
"FileNotFoundError: [Errno 2] No such file or directory: '/home/busrasirin/KYC/TRAIN/data/train_map/6_2_19_2'".

I think this train method requires map_dir files. I don't have map images. How can I access map_images
or generate these images? I have also added the error trace

/home/busrasirin/KYC/TRAIN/cdcn-env/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:129: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Traceback (most recent call last):
  File "train_CDCN.py", line 461, in <module>
    train_test()
  File "train_CDCN.py", line 302, in train_test
    for i, sample_batched in enumerate(dataloader_train):
  File "/home/busrasirin/KYC/TRAIN/cdcn-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/busrasirin/KYC/TRAIN/cdcn-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/busrasirin/KYC/TRAIN/cdcn-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/busrasirin/KYC/TRAIN/cdcn-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/busrasirin/KYC/TRAIN/CDCN/CVPR2020_paper_codes/Load_OULUNPU_train.py", line 231, in __getitem__
    image_x, map_x = self.get_single_image_x(image_path, map_path, videoname)
  File "/home/busrasirin/KYC/TRAIN/CDCN/CVPR2020_paper_codes/Load_OULUNPU_train.py", line 249, in get_single_image_x
    frames_total = len([name for name in os.listdir(map_path) if os.path.isfile(os.path.join(map_path, name))])
FileNotFoundError: [Errno 2] No such file or directory: '/home/busrasirin/KYC/TRAIN/data/train_map/6_2_19_2'

By the way, I made some changes in train_CDCN.py file. These changes are

- modifications to allow CPU to be used as opposed to GPU
- data folder setup modifications
- setted dataloader num_workers=0

Your feedback would be very much appreciated.

**Comment by debasmitdas** [comment]
According to https://github.com/timesler/facenet-pytorch/blob/master/models/mtcnn.py, the MTCNN network required threshold values for face detection.

What threshold values did you choose for the network and whether it was adapted or fixed ?

Also, with your thresholds, did you encounter empty or wrong face detections and how did you deal with those images ?

**Comment by punitha-valli** [comment]
HI,

As per my experience, if you set the nominal threshold (0.5 as per my
remembrance) capture all the faces of a database

**Comment by debasmitdas** [comment]
People, who have tried extracting depth maps using PRNet, which github repository did you find to be most reliable and useful ?

**Comment by punitha-valli** [comment]
hi,
please refer to this repository,

https://github.com/YadiraF/PRNet

Thanks,

**Comment by Celinesiya** [comment]
> @ZitongYu @CuauLuzbel @punitha-valli
> 
> Can you please tell me about the map_dir, Then, also about the train_iamges directory
> 
> I have the oulu-npu dataset
> 
> It will be a great help to my research work
> 
> Thanks in advance

Hi! Have you solved this problem?What should I put into map_dir?Thank you a lot!!

**Comment by maywander** [comment]
Can you share more about how to extract more from videos to images?

**Comment by punitha-valli** [comment]
Increase frames per second, in your python coding so you can able to get
the more number of frames from one video.

**Comment by Deepthi2992** [comment]
Can you please tell me the naming convention of '1_1_01_1.avi', '1_1_01_2.avi','1_1_01_3.avi', 1_1_01_4.avi', '1_1_01_5.avi', '1_1_02_1.avi', '1_1_02_2.avi'. Thanks in advance.

**Comment by punitha-valli** [comment]
Hi Deepthi ,
i have closed this research by 2020, as per my memory, the last digit
represents the FPS (I captured more frames within the FPS). And the
remaining digits represent the video file name with respect the the folder
and sub-folders. There as my own modifications for generating the depth
image as a Data base.

Thanks,
Punitha

**Comment by Deepthi2992** [comment]
Okay , thank you.
