### ISSUE TITLE
Code implementation error?

### ISSUE THREAD

**Issue by amsturdy** [ZitongYu/CDCN#15]
Central Difference Convolution's implementation is'not match with the Eq.(4) of paper ?
kernel_diff should be only related with the center point of inputs' local domain ?
![捕获](https://user-images.githubusercontent.com/18511167/80331653-3765e100-887b-11ea-9fef-aeb14699256c.PNG)

**Comment by ZitongYu** [comment]
Yeah, that's a point-wise convolution, just considering the current position, not local domain

**Comment by Zhengtq** [comment]
@ZitongYu Have you tried only use a normal 3x3 vanilla conv followed by normal 1x1 pointwise conv. The only difference is that the kernel of the 1x1 pointwise conv is new while your the kernel of 1x1 pointwise conv in your  CDC module is generated from the front 3x3 vanilla conv's kernel.

**Comment by punitha-valli** [comment]
@Zhengtq 

@amsturdy 
@ZitongYu 

can you please explain to me about the map_dir, and the oulu_npu dataset has video, but as per the source code Train-images, Dev_images, Test_images are required.



Can you please explain it to me?

I am also a student, so it will be greatly helpful for me to do my research work.

thanks in advance

**Comment by punitha-valli** [comment]
@ZitongYu 
@amsturdy 
@Zhengtq 

@punitha-valli 
![image](https://user-images.githubusercontent.com/52031723/90110967-9135dc80-dd80-11ea-8650-042ab874002f.png)



Even i have the images, in that folder i i cant able to do it,  i cant able to find the reason, is there any way to solve it, 

Thanks in advance

**Comment by punitha-valli** [comment]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3'

Even I have images in this folder,...

How about the def single_iamge_x():

I have confusion in it,

Because i have already splitted up the oulu dataset videos 1_1_01_1 into 1_1_01_1_1, 1_1_01_1_2,1_1_01_1_3 like this....,

def get_single_image_x(self, image_path, map_path, videoname):

    for name in os.listdir(map_path):
        print(name)

    print(os.path.isfile(os.path.join(map_path, videoname)))

    frames_total = len([name for name in os.listdir(map_path) if os.path.isfile(os.path.join(map_path, name))])
    #print(frames_total)
    
    # random choose 1 frame
    for temp in range(500):
        image_id = np.random.randint(1, frames_total-1)
        
        s = "_%03d_scene" % image_id
        image_name = videoname + s + '.jpg'
        bbox_name = videoname + s + '.dat'
        bbox_path = os.path.join(image_path, bbox_name)
        s = "_%03d_depth1D" % image_id
        map_name = videoname + s + '.jpg'
        map_path2 = os.path.join(map_path, map_name)
    
        # some .dat & map files have been missing  
        if os.path.exists(bbox_path) & os.path.exists(map_path2):
            map_x_temp2 = cv2.imread(map_path2, 0)
            if map_x_temp2 is not None:
                break
    
    about this one, 
here the error occurs, FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3',..

any to please, explain to me about it,.

Thanks in advance

@Zhengtq @amsturdy @ZitongYu

**Comment by 610821216** [comment]
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3'
> 
> Even I have images in this folder,...
> 
> How about the def single_iamge_x():
> 
> I have confusion in it,
> 
> Because i have already splitted up the oulu dataset videos 1_1_01_1 into 1_1_01_1_1, 1_1_01_1_2,1_1_01_1_3 like this....,
> 
> def get_single_image_x(self, image_path, map_path, videoname):
> 
> ```
> for name in os.listdir(map_path):
>     print(name)
> 
> print(os.path.isfile(os.path.join(map_path, videoname)))
> 
> frames_total = len([name for name in os.listdir(map_path) if os.path.isfile(os.path.join(map_path, name))])
> #print(frames_total)
> 
> # random choose 1 frame
> for temp in range(500):
>     image_id = np.random.randint(1, frames_total-1)
>     
>     s = "_%03d_scene" % image_id
>     image_name = videoname + s + '.jpg'
>     bbox_name = videoname + s + '.dat'
>     bbox_path = os.path.join(image_path, bbox_name)
>     s = "_%03d_depth1D" % image_id
>     map_name = videoname + s + '.jpg'
>     map_path2 = os.path.join(map_path, map_name)
> 
>     # some .dat & map files have been missing  
>     if os.path.exists(bbox_path) & os.path.exists(map_path2):
>         map_x_temp2 = cv2.imread(map_path2, 0)
>         if map_x_temp2 is not None:
>             break
> 
> about this one, 
> ```
> 
> here the error occurs, FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3',..
> 
> any to please, explain to me about it,.
> 
> Thanks in advance
> 
> @Zhengtq @amsturdy @ZitongYu

I have the same problem.. have you solved it?

**Comment by punitha-valli** [comment]
Hi,

Please make sure about the path of image, and please check the video name ,
and how it's getting the image name


Thank you
