### ISSUE TITLE
关于NAS部分的代码

### ISSUE THREAD

**Issue by PrinceDouble** [ZitongYu/CDCN#16]
您好！麻烦一下，请问关于NAS部分的代码方便分享吗？ 多谢啦！

**Comment by ZitongYu** [comment]
Please refer to the official code DARTS and PC-DARTS, thx.

**Comment by PrinceDouble** [comment]
余博士，能向你请教一些问题吗？关于你2020年cvpr的关于CDCN的那篇论文，我按照你的建议参考了DARTS和PC-DARTS的官方文档，然后复现的你文章中的方法，但是在训练的过程中，遇到了一些问题。我也是用三张1080ti的显卡，发现batch-size设置为16时显存不够，只能设置为4，跑到architect更新时候显存不够。我花了挺多时间在上面复现，遇到这个问题难以解决。希望你能提供更多的复现细节，主要是显存会不够，如果可以能提供源码的话将不胜感激！然后在跨库实验结果和论文中相差很大，能够提供更为详细的跨库实验细节吗？谢谢啦！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fisher Yu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 晚上11:07
收件人:&nbsp;"ZitongYu/CDCN"<CDCN@noreply.github.com&gt;;
抄送:&nbsp;"wondersun"<1299150546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZitongYu/CDCN] 关于NAS部分的代码 (#16)





 
Please refer to the official code DARTS and PC-DARTS, thx.

**Comment by punitha-valli** [comment]
@ZitongYu @PrinceDouble 

After getting the map_score, how to calculate the APCER, BPCER, ACER, ACC, HTER

can you please reply

Hope for a good reply

Thank you

**Comment by punitha-valli** [comment]
@ZitongYu @PrinceDouble @ZitongYu 

After getting the map_score, how to calculate the APCER, BPCER, ACER, ACC, HTER

can you please reply

Hope for a good reply

Thank you
