### ISSUE TITLE
麻烦问一下 您可不可以分享一下这个比赛的数据集

### ISSUE THREAD

**Issue by silvercherry** [ZitongYu/CDCN#2]
最近一直想用这个集，但是比赛已经截止了，申请不到。博主可以分享一下吗，麻烦您了！
感激不尽！

**Comment by ZitongYu** [comment]
比赛只有这数据集的一小部分，且测试集没label，完整的数据集估计得他们中了ECCV才公开吧~~你如果还是想要的话邮件我私聊咯

**Comment by boozyguo** [comment]
@silvercherry  是指 Oulu-npu数据集合？

**Comment by RayTang88** [comment]
@ZitongYu 同求一下这个数据集，非常感谢！！！

**Comment by silvercherry** [comment]
> @silvercherry 是指 Oulu-npu数据集合？
嗯嗯~

**Comment by xudou3** [comment]
@ZitongYu 同求一下这个数据集，非常感谢！！！

**Comment by Kraken000** [comment]
> > @silvercherry 是指 Oulu-npu数据集合？
> > 嗯嗯~

老哥，数据能发我一份吗，感谢感谢

**Comment by Okersira** [comment]
> @silvercherry 是指 Oulu-npu数据集合？

您好，这边能分享一下OULU_NPU数据集吗，虽然我已经发了邮件申请，但是我们学校的邮箱现在挂在腾讯企业邮箱上，好像被收件方直接block掉了
