### ISSUE TITLE
关于测试阶段，深度图的使用

### ISSUE THREAD

**Issue by songminguo2333** [ZitongYu/CDCN#23]
您好，
    您在CVPR2020_paper_codes/train_CDCN.py 中test阶段，使用了binary map from PRNet，用作norm score
    请问为什么要利用测试数据对应的深度图，用来norm score？
     code:
        “test_maps = sample_batched['val_map_x'].cuda()   # binary map from PRNet”
        “score_norm = torch.sum(map_x)/torch.sum(test_maps[:,frame_t,:,:])”

**Comment by yashasvi97** [comment]
Yeah even I had this doubt as to why depth maps norms are used as spoof scores, as opposed to training the network to output some scalar value. Any insights on this would be much appreciated @ZitongYu 
Thanks

**Comment by XinyingZheng** [comment]
> 您好，
> 您在CVPR2020_paper_codes/train_CDCN.py 中test阶段，使用了binary map from PRNet，用作norm score
> 请问为什么要利用测试数据对应的深度图，用来norm score？
> code:
> “test_maps = sample_batched['val_map_x'].cuda() # binary map from PRNet”
> “score_norm = torch.sum(map_x)/torch.sum(test_maps[:,frame_t,:,:])”
你跑通了吗，如果是假体，test map 全为0，加和也是0，作为分母，我的程序就出现了NAN

**Comment by liuyuchen6666** [comment]
@XinyingZheng 您好 请问您是如何将OULU本身的视频 提取为帧 有什么需要遵循的规则吗 比如多久提取一次帧

**Comment by sitadivon** [comment]
> 您好，
> 您在CVPR2020_paper_codes/train_CDCN.py 中test阶段，使用了binary map from PRNet，用作norm score
> 请问为什么要利用测试数据对应的深度图，用来norm score？
> code:
> “test_maps = sample_batched['val_map_x'].cuda() # binary map from PRNet”
> “score_norm = torch.sum(map_x)/torch.sum(test_maps[:,frame_t,:,:])”

@ZitongYu Could you provide an explanation? I have the same doubts.
