### ISSUE TITLE
Pre-processing for SiW-M experiments

### ISSUE THREAD

**Issue by pratik18v** [ZitongYu/CDCN#26]
Hi,
Thank you for sharing your code. I am trying to replicate your SiW_M experiments but are getting different numbers for certain test spoof types. I think this might be due to difference in the way we have pre-processed the videos to obtain face-centered frames (and depth masks). Can you please provide details regarding the steps you took to obtain the training (and testing) data for your model from the videos in the SiW_M dataset?

Thank you!

**Comment by VuHoangvn** [comment]
If you know how to generate data, please share with me!
Thank you so much!

**Comment by Alpkant** [comment]
I am also looking for the same thing.

**Comment by debasmitdas** [comment]
Same here. Does anybody have the pre-processing for SiW dataset ?

**Comment by mike07026** [comment]
@debasmitdas Can you share SiW dataset?

**Comment by ghost** [comment]
hey,
i need SiW-M database , how to download this database ?

**Comment by dxtyut** [comment]
Can you share me the SiW-M and OULU-NPU datasets. I use them for academic research, not for anything else. I have applied for the datasets many times, but failed.
zhoudaoxiang@tyut.edu.cn
