### ISSUE TITLE
BinaryMask generate in  code for Track2 Single-modal

### ISSUE THREAD

**Issue by xiao-keeplearning** [ZitongYu/CDCN#3]
Hi, Thank you share your great work. I found that the binary mask is used in this CVPRW competition. How much do you think this alternative method will affect your algorithm performance?
```
    for i in range(32):
            for j in range(32):
                if image_x_temp_gray[i,j]>0:
                    binary_mask[i,j]=1
                else:
                    binary_mask[i,j]=0
```

**Comment by ZitongYu** [comment]
I have no time to test other supervision in this competition with limited time. But I think using depth label > binary mask > binary scalar score

**Comment by xiao-keeplearning** [comment]
Thanks to your replay

**Comment by masouduut94** [comment]
Do you have pretrained network from this project @xiao-keeplearning ?
If so, let me know.

I am researching in this field. Can you help me find good resources for anti-spoofing project?
