### ISSUE TITLE
产生深度图

### ISSUE THREAD

**Issue by 22wei22** [ZitongYu/CDCN#30]
你好，我使用https://github.com/clks-wzz/PRNet-Depth-Generation产生深度图
![image](https://user-images.githubusercontent.com/25198185/97847374-7c873600-1d2a-11eb-9295-0145af6e8100.png)
他返回的数值是y1,x1,w,h
你的代码里面也是y2=y1+w,但是正常情况下应该是w和x一块计算的，不应该是x2=x1+w？
![image](https://user-images.githubusercontent.com/25198185/97847554-bfe1a480-1d2a-11eb-9426-79017044bb42.png)

**Comment by liuyuchen6666** [comment]
这个代码里面有计算深度图的部分吗？

**Comment by vu-nguyenhyit** [comment]
https://github.com/YadiraF/PRNet/tree/master/Data/net-data
It's here

> Is there a part to calculate the depth map in this code?
