### ISSUE TITLE
Train list, val list and test list. Documentation

### ISSUE THREAD

**Issue by himansh1314** [ZitongYu/CDCN#36]
Can you please let me know what is train list, test list and val list in train.py in CVPR2020 paper codes? Also, some documentation about how to train the model would be helpful.

**Comment by abraar-raza** [comment]
> Can you please let me know what is train list, test list and val list in train.py in CVPR2020 paper codes? Also, some documentation about how to train the model would be helpful.

Hi, were you able to figure anything out regarding this issue?
