### ISSUE TITLE
Theta =0 is one point higher than that of Theta =0.7

### ISSUE THREAD

**Issue by XinyingZheng** [ZitongYu/CDCN#38]
By comparing and training CDCN, it is found that the accuracy of general convolution using Theta =0 is one point higher than that of Theta =0.7. Does anyone have the same result as me

**Comment by RizhaoCai** [comment]
What are your exact result numbers? @XingyingZheng

> By comparing and training CDCN, it is found that the accuracy of general convolution using Theta =0 is one point higher than that of Theta =0.7. Does anyone have the same result as me
