### ISSUE TITLE
关于跨库实验

### ISSUE THREAD

**Issue by lz28lz28** [ZitongYu/CDCN#4]
您好，感谢您开源工作代码，我想知道关于replay和casia的跨库实验中，每个测试数据集的结果判别的threshold如何获得（对于replay数据集，通过他的dev部分获得嘛？那么casia呢，自己将测试集分成dev和test嘛），或者说是通过其他方法进行每个测试集video的结果判别？。十分感谢，期待您的回复！

**Comment by ZitongYu** [comment]
跨库没有很标准统一的做法，建议取最佳阈值吧

**Comment by silvercherry** [comment]
> 您好，感谢您开源工作代码，我想知道关于replay和casia的跨库实验中，每个测试数据集的结果判别的threshold如何获得（对于replay数据集，通过他的dev部分获得嘛？那么casia呢，自己将测试集分成dev和test嘛），或者说是通过其他方法进行每个测试集video的结果判别？。十分感谢，期待您的回复！

请问一下您跨库实验的效果怎么样呀
我这边复现了了一下，但是效果不是很好

**Comment by lz28lz28** [comment]
> > 您好，感谢您开源工作代码，我想知道关于replay和casia的跨库实验中，每个测试数据集的结果判别的threshold如何获得（对于replay数据集，通过他的dev部分获得嘛？那么casia呢，自己将测试集分成dev和test嘛），或者说是通过其他方法进行每个测试集video的结果判别？。十分感谢，期待您的回复！
> 
> 请问一下您跨库实验的效果怎么样呀
> 我这边复现了了一下，但是效果不是很好

这个也是一楼的我

**Comment by punitha-valli** [comment]
@lz28lz28 @silvercherry @ZitongYu 
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3'

Even I have images in this folder,...

How about the def single_iamge_x():

I have confusion in it,

Because i have already splitted up the oulu dataset videos 1_1_01_1 into 1_1_01_1_1, 1_1_01_1_2,1_1_01_1_3 like this....,

def get_single_image_x(self, image_path, map_path, videoname):

    for name in os.listdir(map_path):
        print(name)

    print(os.path.isfile(os.path.join(map_path, videoname)))

    frames_total = len([name for name in os.listdir(map_path) if os.path.isfile(os.path.join(map_path, name))])
    #print(frames_total)
    
    # random choose 1 frame
    for temp in range(500):
        image_id = np.random.randint(1, frames_total-1)
        
        s = "_%03d_scene" % image_id
        image_name = videoname + s + '.jpg'
        bbox_name = videoname + s + '.dat'
        bbox_path = os.path.join(image_path, bbox_name)
        s = "_%03d_depth1D" % image_id
        map_name = videoname + s + '.jpg'
        map_path2 = os.path.join(map_path, map_name)
    
        # some .dat & map files have been missing  
        if os.path.exists(bbox_path) & os.path.exists(map_path2):
            map_x_temp2 = cv2.imread(map_path2, 0)
            if map_x_temp2 is not None:
                break
    
    about this one, 
here the error occurs, FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3',..

any to please, explain to me about it,.

Thanks in advance

**Comment by liuyuchen6666** [comment]
@lz28lz28 @silvercherry 请问您复现的时候 原始的视频数据是间隔几秒划分成帧的呢？另外depth_map和.dat是使用PRNet和MTCNN产生的吗，有相应的代码项目可以参考吗 这对我的研究很重要 感谢您

**Comment by maywander** [comment]
> @lz28lz28 @silvercherry @ZitongYu FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3'
> 
> Even I have images in this folder,...
> 
> How about the def single_iamge_x():
> 
> I have confusion in it,
> 
> Because i have already splitted up the oulu dataset videos 1_1_01_1 into 1_1_01_1_1, 1_1_01_1_2,1_1_01_1_3 like this....,
> 
> def get_single_image_x(self, image_path, map_path, videoname):
> 
> ```
> for name in os.listdir(map_path):
>     print(name)
> 
> print(os.path.isfile(os.path.join(map_path, videoname)))
> 
> frames_total = len([name for name in os.listdir(map_path) if os.path.isfile(os.path.join(map_path, name))])
> #print(frames_total)
> 
> # random choose 1 frame
> for temp in range(500):
>     image_id = np.random.randint(1, frames_total-1)
>     
>     s = "_%03d_scene" % image_id
>     image_name = videoname + s + '.jpg'
>     bbox_name = videoname + s + '.dat'
>     bbox_path = os.path.join(image_path, bbox_name)
>     s = "_%03d_depth1D" % image_id
>     map_name = videoname + s + '.jpg'
>     map_path2 = os.path.join(map_path, map_name)
> 
>     # some .dat & map files have been missing  
>     if os.path.exists(bbox_path) & os.path.exists(map_path2):
>         map_x_temp2 = cv2.imread(map_path2, 0)
>         if map_x_temp2 is not None:
>             break
> 
> about this one, 
> ```
> 
> here the error occurs, FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/face_anti_spoofing/dataset/OULUNPU/Data/demo/Train/Depth_map_1/1_1_01_3',..
> 
> any to please, explain to me about it,.
> 
> Thanks in advance

Can you share more about how to split videos 1_1_01_1 into 1_1_01_1_1, 1_1_01_1_2,1_1_01_1_3 and how to obtain .dat files?
