### ISSUE TITLE
Patch Exchange Augmentation face image size?

### ISSUE THREAD

**Issue by ngoanpv** [ZitongYu/CDCN#41]
Hi @ZitongYu, 
When using Patch Exchange Augmentation, what the face image size using to extract patches, the original face detected, or resized face (ex 256x256)?

**Comment by cvengneer** [comment]
Hi @ngoanpv,

Were you able to implement the PE Augmentation? or where I can find the code for it?
Thank you!

**Comment by Saurav-31** [comment]
@cvengneer @ngoanpv @ZitongYu 

Any idea where can I find the implementation for patch exchange augmentation?
