### ISSUE TITLE
How did you the RankSVM exactly in NAS-FAS paper?

### ISSUE THREAD

**Issue by thimabru1010** [ZitongYu/CDCN#42]
Thanks for your contribution with the NAS-FAS paper!

I like the idea of aggregating the video input into a Static-Dynamic image, but something on RankSVM is not clear for me.

How did u implement RankSVM to obtain the Dynamic image? 
Is the Dynamic image "D" is the weight of the SVM algorithm?

I am trying to follow this idea of RankSVM: https://www.cnblogs.com/bentuwuying/p/6683832.html

So, you ended just preprocessing the frames into a mean image S_i (using K frames) and then subtracting them to create the proper input to RankSVM? Did you also subtract in the opposite way to obtain negative labels?

After preparing data this way you just trained an SVM with sci-kit learn using Hinge loss? After training for what I understood, you want to obtain D that is exactly the parameters of SVM. Therefore, suppose I am using scikit-learn for example, I just need to use the get_params method and then perform the max-min normalization to obtain the Static-Dynamic image?

**Comment by xiao-keeplearning** [comment]
Hi, I am also interested in this paper. [This](https://github.com/AlexanderParkin/CASIA-SURF_CeFA/blob/205d3d976523ed0c15d1e709ed7f21d50d7cf19b/at_learner_core/at_learner_core/utils/transforms.py#L553) may be a good implementation, have you paid attention to it?

How have you been doing about this paper recently?
