### ISSUE TITLE
有人能复现论文中的这个结果吗？我复现的结果差很多

### ISSUE THREAD

**Issue by PangziZhang523** [ZitongYu/CDCN#43]

**Comment by HeyMelody** [comment]
您好，请问能分享一下oulu-npu数据集吗？下载链接现在已经无法访问了，十分感谢。这是我的邮箱：hemelody@qq.com

**Comment by RizhaoCai** [comment]
请问你复现的是CDC还是DualCrossCDC?

**Comment by liguiyuan** [comment]
> 您好，请问能分享一下oulu-npu数据集吗？下载链接现在已经无法访问了，十分感谢。这是我的邮箱：[hemelody@qq.com](mailto:hemelody@qq.com)

你好，请问你找到数据集了吗？

**Comment by liguiyuan** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月26日(周四) 下午3:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZitongYu/CDCN] 有人能复现论文中的这个结果吗？我复现的结果差很多 (#43)




   
***@***.***
  
你好，请问你找到数据集了吗？
  
我让导师签EULA的时候我导说他们组已经解散了，他帮我要了一份，但是不能分享，不好意思
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fiona-lxd** [comment]
> > > 您好，请问能分享一下oulu-npu数据集吗？下载链接现在已经无法访问了，十分感谢。这是我的邮箱：[hemelody@qq.com](mailto:hemelody@qq.com)
> > 
> > 
> > 你好，请问你找到数据集了吗？
> 
> 我让导师签EULA的时候我导说他们组已经解散了，他帮我要了一份，但是不能分享，不好意思

请问你有训好的ckpt吗，Thanks in advance. lxd1030@mail.ustc.edu.cn

**Comment by JayJ-1997** [comment]
请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了

**Comment by Miranda-h** [comment]
> 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了

我是6%

**Comment by milky-tea-1997** [comment]
> > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> 
> 我是6%

我怀疑作者放的指标是验证集的.....

**Comment by HeyMelody** [comment]
> > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > 
> > 
> > 我是6%
> 
> 我怀疑作者放的指标是验证集的.....

我验证集也只有0.9% T_T

**Comment by HeyMelody** [comment]
> > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > 
> > 
> > 我是6%
> 
> 我怀疑作者放的指标是验证集的...

> > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > 
> > 
> > 我是6%
> 
> 我怀疑作者放的指标是验证集的.....

我验证集也只有0.6% T_T

**Comment by Miranda-h** [comment]
> > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > 
> > 
> > 我是6%
> 
> 我怀疑作者放的指标是验证集的.....

我验证集也只有0.6% T_T

**Comment by milky-tea-1997** [comment]
> > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > 
> > > 
> > > 我是6%
> > 
> > 
> > 我怀疑作者放的指标是验证集的.....
> 
> 我验证集也只有0.6% T_T
我仔细看了一下protocol，我看第一种协议的测试集的采样场景变了，相当于跨域了感觉，训练集和验证集倒是同样的场景，所有按道理测试集的指标会下降吧，个人感觉

**Comment by milky-tea-1997** [comment]
> > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > 
> > 
> > 我是6%
> 
> 我怀疑作者放的指标是验证集的.....

等一下，是6%还是0.6%，这可差了太多了啊

**Comment by dxtyut** [comment]
Can you share me the OULU-NPU dataset.  I use it for academic research, not for anything else. I have applied for this dataset many times, but failed. 
zhoudaoxiang@tyut.edu.cn

**Comment by dxtyut** [comment]
Can you share me the SiW-M and OULU-NPU datasets. I use them for academic research, not for anything else. I have applied for the datasets many times, but failed.
zhoudaoxiang@tyut.edu.cn

**Comment by Miranda-h** [comment]
> > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > 
> > > 
> > > 我是6%
> > 
> > 
> > 我怀疑作者放的指标是验证集的.....
> 
> 等一下，是6%还是0.6%，这可差了太多了啊

测试集上6%，救救孩子，可以留个联系方式交流一下吗

**Comment by Aruen24** [comment]
多模态训练数据的结构是什么样的？

**Comment by jamesdongdong** [comment]
> > > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > > 
> > > > 
> > > > 我是6%
> > > 
> > > 
> > > 我怀疑作者放的指标是验证集的.....
> > 
> > 
> > 等一下，是6%还是0.6%，这可差了太多了啊
> 
> 测试集上6%，救救孩子，可以留个联系方式交流一下吗

请问深度图都是用TensorFlow版本的PRnet生成的吗，我这边感觉好慢16s生成一张。。。

**Comment by roger-cv** [comment]
> > > > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > > > 
> > > > > 
> > > > > 我是6%
> > > > 
> > > > 
> > > > 我怀疑作者放的指标是验证集的.....
> > > 
> > > 
> > > 等一下，是6%还是0.6%，这可差了太多了啊
> > 
> > 
> > 测试集上6%，救救孩子，可以留个联系方式交流一下吗
> 
> 请问深度图都是用TensorFlow版本的PRnet生成的吗，我这边感觉好慢16s生成一张。。。

我是pytorch版的

**Comment by Miranda-h** [comment]
> > > > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > > > 
> > > > > 
> > > > > 我是6%
> > > > 
> > > > 
> > > > 我怀疑作者放的指标是验证集的.....
> > > 
> > > 
> > > 等一下，是6%还是0.6%，这可差了太多了啊
> > 
> > 
> > 测试集上6%，救救孩子，可以留个联系方式交流一下吗
> 
> 请问深度图都是用TensorFlow版本的PRnet生成的吗，我这边感觉好慢16s生成一张。。。

pytorch版，3090单卡和你的时间差不多

**Comment by roger-cv** [comment]
> > > > > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > > > > 
> > > > > > 
> > > > > > 我是6%
> > > > > 
> > > > > 
> > > > > 我怀疑作者放的指标是验证集的.....
> > > > 
> > > > 
> > > > 等一下，是6%还是0.6%，这可差了太多了啊
> > > 
> > > 
> > > 测试集上6%，救救孩子，可以留个联系方式交流一下吗
> > 
> > 
> > 请问深度图都是用TensorFlow版本的PRnet生成的吗，我这边感觉好慢16s生成一张。。。
> 
> pytorch版，3090单卡和你的时间差不多
请问你们也是用map_score作为预测得分吗？（和CDCN评测方法一样？）

**Comment by kwong292521** [comment]
> > > > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > > > 
> > > > > 
> > > > > 我是6%
> > > > 
> > > > 
> > > > 我怀疑作者放的指标是验证集的.....
> > > 
> > > 
> > > 等一下，是6%还是0.6%，这可差了太多了啊
> > 
> > 
> > 测试集上6%，救救孩子，可以留个联系方式交流一下吗
> 
> 请问深度图都是用TensorFlow版本的PRnet生成的吗，我这边感觉好慢16s生成一张。。。

我用3ddfa-v2生成的，很快

**Comment by sherlockers** [comment]
> 
请问你跑cdcn花多长时间？

**Comment by AlingJia** [comment]
> 

请问你是验证集上0.6%，测试集上6%吗！我也是测试集比验证集大很多，请问为啥会出现测试集比验证集大很多这种现象啊

**Comment by AlingJia** [comment]
> > 
> 
> 请问你是验证集上0.6%，测试集上6%吗！我也是测试集比验证集大很多，请问为啥会出现测试集比验证集大很多这种现象啊

**Comment by AlingJia** [comment]
> > > > 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
> > > 
> > > 
> > > 我是6%
> > 
> > 
> > 我怀疑作者放的指标是验证集的.....
> 
> 我验证集也只有0.6% T_T


请问你是验证集上0.6%，测试集上6%吗！我也是测试集比验证集大很多，请问为啥会出现测试集比验证集大很多这种现象啊
@[HeyMelody](https://github.com/HeyMelody)

**Comment by Miranda-h** [comment]
我把训练样本量增大了些就好了，你可以试试



------------------ 原始邮件 ------------------
发件人: AiLing ***@***.***&gt;
发送时间: 2022年3月25日 10:16
收件人: ZitongYu/CDCN ***@***.***&gt;
抄送: 肥猫警长 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZitongYu/CDCN] 有人能复现论文中的这个结果吗？我复现的结果差很多 (#43)





     
请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了
  
我是6%
  
我怀疑作者放的指标是验证集的.....
  
我验证集也只有0.6% T_T
  
请问你是验证集上0.6%，测试集上6%吗！我也是测试集比验证集大很多，请问为啥会出现测试集比验证集大很多这种现象啊
 @HeyMelody

**Comment by AlingJia** [comment]
> 我把训练样本量增大了些就好了，你可以试试
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: AiLing ***@***.***&gt; 发送时间: 2022年3月25日 10:16 收件人: ZitongYu/CDCN ***@***.***&gt; 抄送: 肥猫警长 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [ZitongYu/CDCN] 有人能复现论文中的这个结果吗？我复现的结果差很多 (#43) 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了 我是6% 我怀疑作者放的指标是验证集的..... 我验证集也只有0.6% T_T 请问你是验证集上0.6%，测试集上6%吗！我也是测试集比验证集大很多，请问为啥会出现测试集比验证集大很多这种现象啊 @HeyMelody — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问你在计算测试集ACER时，也是将测试集中得到的预测值和验证集的阈值相比吗（也就是这个code的计算测试集的ACER方法）

**Comment by Miranda-h** [comment]
嗯，是的。






------------------ 原始邮件 ------------------
发件人: AiLing ***@***.***&gt;
发送时间: 2022年3月25日 10:57
收件人: ZitongYu/CDCN ***@***.***&gt;
抄送: 肥猫警长 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ZitongYu/CDCN] 有人能复现论文中的这个结果吗？我复现的结果差很多 (#43)





  
我把训练样本量增大了些就好了，你可以试试
 …
 ------------------ 原始邮件 ------------------ 发件人: AiLing @.&gt; 发送时间: 2022年3月25日 10:16 收件人: ZitongYu/CDCN @.&gt; 抄送: 肥猫警长 @.&gt;, Comment @.&gt; 主题: Re: [ZitongYu/CDCN] 有人能复现论文中的这个结果吗？我复现的结果差很多 (#43) 请问你在OULU-NPU protocol 1上面ACER大概多少，我也发觉论文中的指标有点过高了 我是6% 我怀疑作者放的指标是验证集的..... 我验证集也只有0.6% T_T 请问你是验证集上0.6%，测试集上6%吗！我也是测试集比验证集大很多，请问为啥会出现测试集比验证集大很多这种现象啊 @HeyMelody — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
请问你在计算测试集ACER时，也是将测试集中得到的预测值和验证集的阈值相比吗（也就是这个code的计算测试集的ACER方法）
