### ISSUE TITLE
Where can I get the image and .dat files?

### ISSUE THREAD

**Issue by yumna4** [ZitongYu/CDCN#44]
Hi,

I got access to the OULU dataset, and it contains .txt and .avi files. This repo refers to image and .dat files as (1_1_22_4_107_scene.dat). How can I get these files?

(https://github.com/ZitongYu/CDCN/blob/master/CVPR2020_paper_codes/Load_OULUNPU_train.py#L281)

Thank you!

**Comment by debasmitdas** [comment]
Do you know what are those .txt files and how do you get .dat files ?

**Comment by dimasheva1** [comment]
@yumna4 Could you share with me the oulu-npu dataset? Because the server being down, and the contact email address being useless, renders all tries to officially obtain the dataset in vain and fruitless!

My email is [dimyich24@gmail.com](mailto:dimyich24@gmail.com)

**Comment by alletsr** [comment]
> Hi,
> 
> I got access to the OULU dataset, and it contains .txt and .avi files. This repo refers to image and .dat files as (1_1_22_4_107_scene.dat). How can I get these files?
> 
> (https://github.com/ZitongYu/CDCN/blob/master/CVPR2020_paper_codes/Load_OULUNPU_train.py#L281)
> 
> Thank you!

Did you got answer

**Comment by abhirajasp** [comment]
the .dat files are depth maps, that you have to generate using 3DDFA repo
