### ISSUE TITLE
A problem of Validation/ Test phase.

### ISSUE THREAD

**Issue by quangtn266** [ZitongYu/CDCN#45]
Hi author,

Thank you for your work.

Currently, I implement your work on my data. However, in val/test, I got one issue, my depth map score for val/ test have inf and nan score. In your work, I just custom Load_train/valtest to adopt my data.
![Screenshot from 2021-09-28 08-07-39](https://user-images.githubusercontent.com/50879191/135005757-3dc108bf-d53e-46c9-9bc3-fadf2c9e60df.png)

Can you give me some advice to fix this issue ?

Thank you

**Comment by Saurav-31** [comment]
`score_norm = torch.sum(map_x)/torch.sum(val_maps[:,frame_t,:,:])`

This code calculates map score while validation and testing. If ground truth depth map is zeros, score norm will become infinity. Cross check that.

**Comment by quangtn266** [comment]
> `score_norm = torch.sum(map_x)/torch.sum(val_maps[:,frame_t,:,:])`
> 
> This code calculates map score while validation and testing. If ground truth depth map is zeros, score norm will become infinity. Cross check that.

Thank you for your answer, I already fix this issue, because I use images for training and testing, so the current formula here isn't proper for my case.

**Comment by Zhangjw0211** [comment]
Excuse me, how to correct this code

**Comment by Zhangjw0211** [comment]
@Saurav-31 @quangtn266  If ground truth depth map is zeros, how to compute the score norm in the val and test? Thank you so much.
