### ISSUE TITLE
Question about normalization?

### ISSUE THREAD

**Issue by quangtn266** [ZitongYu/CDCN#46]
Hi author,

I have one question about normalization ? Currently I use Image data for training, not for video as you. When I run inference code for video by getting frames, the model can't detect spoofing object. I realize that you use normalization for your frame.
![Screenshot from 2021-10-17 09-46-54](https://user-images.githubusercontent.com/50879191/137608697-dec828c0-00f2-461a-8e86-41b9a285c31e.png)

I wonder does it affects to the performance of model ?

**Comment by RizhaoCai** [comment]
Have you figured why is it?@quangtn266

> Hi author,
> 
> I have one question about normalization ? Currently I use Image data for training, not for video as you. When I run inference code for video by getting frames, the model can't detect spoofing object. I realize that you use normalization for your frame. ![Screenshot from 2021-10-17 09-46-54](https://user-images.githubusercontent.com/50879191/137608697-dec828c0-00f2-461a-8e86-41b9a285c31e.png)
> 
> I wonder does it affects to the performance of model ?
