### ISSUE TITLE
cvprw2020中的BinaryMask疑问

### ISSUE THREAD

**Issue by tfygg** [ZitongYu/CDCN#8]
感谢您的开源。有个疑问，为何这里是使用灰度图生产mask，而不是直接使用depth map？
https://github.com/ZitongYu/CDCN/blob/80033bf67106254973f1f4df34dde4ab6e738748/FAS_challenge_CVPRW2020/Track2%20Single-modal/model1_pytorch/Loadtemporal_BinaryMask_train.py#L222

**Comment by ZitongYu** [comment]
因为比赛规则不能用depth map，不能使用额外模型生成depth。。。

**Comment by tfygg** [comment]
感谢您的回复。
可以理解为：生成一个近似的depth map么？但对于一般的RGB模态的活体检测，采集的人脸照片都没有做face parsing，那如何生成mask呢，制作一个近似的depth map呢？

**Comment by ZitongYu** [comment]
可以看回文章里面的depth generation章节

**Comment by tfygg** [comment]
发现论文和code不一致。
论文里是这样：
 In the testing stage, we calculate the mean value of the predicted depth map as the final score.
但是，paper code中是这样：
https://github.com/ZitongYu/CDCN/blob/2fe27494c022d8fef5f90b87da89b24273cc63ea/CVPR2020_paper_codes/Load_OULUNPU_valtest.py#L182

code有误？temp是resize后的图像，取值范围是0~255。还是哪里理解有误呢？

**Comment by yayflying** [comment]
感谢开源！代码中
            np.where(temp < 1, temp, 1)
是不是并没有起作用

**Comment by lalalanding** [comment]
我想问一下，不使用prnet生成的深度图和使用结果变化大吗？

**Comment by lalalanding** [comment]
tfygg，你好 方便留一下邮箱一起探讨探讨吗
@tfygg

**Comment by tfygg** [comment]
> tfygg，你好 方便留一下邮箱一起探讨探讨吗
> @tfygg

785039861@qq.com

**Comment by FelixZhang7** [comment]
@lalalanding @tfygg 同问不使用prnet生成的深度图而使用比赛中的灰度二值图效果哪个更好？
