### ISSUE TITLE
关于单模型预测标签的问题

### ISSUE THREAD

**Issue by cswwp** [ZitongYu/CDCN#9]
你好， 我发现单模型cdcn在计算loss的时候只有absolute_loss 和contrastive_loss， 难道对应的类别（攻击和真人）没有计算loss吗？网络中也没有发现对应的关于真假体的分类层，可以解释下吗？感谢

![image](https://user-images.githubusercontent.com/11901683/78117258-0212d280-7438-11ea-9012-2ff7ebddaa88.png)

**Comment by ZitongYu** [comment]
> 你好， 我发现单模型cdcn在计算loss的时候只有absolute_loss 和contrastive_loss， 难道对应的类别（攻击和真人）没有计算loss吗？网络中也没有发现对应的关于真假体的分类层，可以解释下吗？感谢
> 
> ![image](https://user-images.githubusercontent.com/11901683/78117258-0212d280-7438-11ea-9012-2ff7ebddaa88.png)

也可以加多个branch (fc层) 来补个cross-entropy loss，可能能再提高一点性能。。。这个做法主要是参考 Auxiliary CVPR2018 那篇文章啦，具体原因（更有针对性地学习，直接binary分类loss不保证能学到spoofing-intrinsic的特征）和细节参考我们文章和Auxiliary文章。

**Comment by cswwp** [comment]
> > 你好， 我发现单模型cdcn在计算loss的时候只有absolute_loss 和contrastive_loss， 难道对应的类别（攻击和真人）没有计算loss吗？网络中也没有发现对应的关于真假体的分类层，可以解释下吗？感谢
> > ![image](https://user-images.githubusercontent.com/11901683/78117258-0212d280-7438-11ea-9012-2ff7ebddaa88.png)
> 
> 也可以加多个branch (fc层) 来补个cross-entropy loss，可能能再提高一点性能。。。这个做法主要是参考 Auxiliary CVPR2018 那篇文章啦，具体原因（更有针对性地学习，直接binary分类loss不保证能学到spoofing-intrinsic的特征）和细节参考我们文章和Auxiliary文章。
可是最后提交的应该是每张rgb的real or fake 标签吧， 直接预测深度图， 最后还有其他的后处理成对应的submission？还是有别的什么操作？

**Comment by soledad-deng** [comment]
同问，测试时得到的map_score在[0,1]之间，与最终的fake or real分类有啥关联？是有个阈值吗？
